load("@rules_cc//cc:defs.bzl", "cc_test")
load("//tools/lint:linters.bzl", "clang_tidy", "clang_tidy_test")

cc_test(
    name = "currency_tests",
    srcs = ["currency_tests.cpp"],
    tags = ["no_sanitize"],
    deps = [
        "//core/src:currency",
        "@googletest//:gtest_main",
    ],
)

clang_tidy_test(
    name = "currency_tidy_tests",
    srcs = ["//core/src:currency"],
)

cc_test(
    name = "money_tests",
    srcs = ["money_tests.cpp"],
    tags = ["no_sanitize"],
    deps = [
        "//core/src:money",
        "@googletest//:gtest_main",
    ],
)

clang_tidy_test(
    name = "money_tidy_tests",
    srcs = ["//core/src:money"],
)

cc_test(
    name = "transaction_tests",
    srcs = ["transaction_tests.cpp"],
    tags = ["no_sanitize"],
    deps = [
        "//core/src:transaction",
        "@googletest//:gtest_main",
    ],
)

clang_tidy_test(
    name = "transaction_tidy_tests",
    srcs = ["//core/src:transaction"],
)
