name: Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Cache Bazel
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7
        with:
          path: |
            ~/.cache/bazel
            ~/.cache/bazelisk
          key: bazel-check-${{ runner.os }}-${{ hashFiles('**/*.bzl', '**/BUILD.bazel', 'MODULE.bazel') }}

      - name: Install Bazelisk
        uses: bazelbuild/setup-bazelisk@b39c379c82683a5f25d34f0d062761f62693e0b2

      - name: Format check
        run: bazel run //tools/format:format.check

  lint-tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Cache Bazel
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7
        with:
          path: |
            ~/.cache/bazel
            ~/.cache/bazelisk
          key: bazel-check-${{ runner.os }}-${{ hashFiles('**/*.bzl', '**/BUILD.bazel', 'MODULE.bazel') }}

      - name: Install Bazelisk
        uses: bazelbuild/setup-bazelisk@b39c379c82683a5f25d34f0d062761f62693e0b2

      - name: Lint / Tidy
        run: bazel build //... --config=tidy

  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        config: [debug, release, sanitized]

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Cache Bazel
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7
        with:
          path: |
            ~/.cache/bazel
            ~/.cache/bazelisk
          key: bazel-check-${{ runner.os }}-${{ matrix.config }}-${{ hashFiles('**/*.bzl', '**/BUILD.bazel', 'MODULE.bazel') }}

      - name: Install Bazelisk
        uses: bazelbuild/setup-bazelisk@b39c379c82683a5f25d34f0d062761f62693e0b2

      - name: Build
        run: bazel build //... --config=${{ matrix.config }}

  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        config: [debug, release, asan]

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Cache Bazel
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7
        with:
          path: |
            ~/.cache/bazel
            ~/.cache/bazelisk
          key: bazel-check-${{ runner.os }}-${{ matrix.config }}-${{ hashFiles('**/*.bzl', '**/BUILD.bazel', 'MODULE.bazel') }}

      - name: Install Bazelisk
        uses: bazelbuild/setup-bazelisk@b39c379c82683a5f25d34f0d062761f62693e0b2

      - name: Test
        run: bazel test //... --config=${{ matrix.config }}
