name: Check PR Dependencies

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  pull-requests: read
  statuses: write

jobs:
  check-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Check Depends-On
        uses: depends-on/depends-on-action@c7ac9a6932a7069e83aef80c202d9f60f91e43fd
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
